# R Usage Examples for schard-based H5AD Conversion (v2.0)
# Generated by schard conversion script v2.0

library(schard)
library(Seurat)
library(Signac)
library(SingleCellExperiment)

# Example 1: Basic H5AD to Seurat conversion
convert_basic_seurat <- function(h5ad_file) {
    cat("Converting H5AD to Seurat object using schard\n")

    # Load as Seurat object
    seurat_obj <- schard::h5ad2seurat(h5ad_file)

    # Basic inspection
    cat("Object summary:\n")
    print(seurat_obj)

    # Check available assays
    cat("Available assays:", paste(names(seurat_obj@assays), collapse = ", "), "\n")

    # Check reductions
    if (length(seurat_obj@reductions) > 0) {
        cat("Available reductions:", paste(names(seurat_obj@reductions), collapse = ", "), "\n")

        # Plot first available reduction
        reduction_name <- names(seurat_obj@reductions)[1]
        cat("Plotting", reduction_name, "\n")
        print(DimPlot(seurat_obj, reduction = reduction_name))
    }

    return(seurat_obj)
}

# Example 2: Load raw counts instead of processed
convert_raw_seurat <- function(h5ad_file) {
    cat("Converting H5AD to Seurat with raw counts\n")

    # Load raw counts
    seurat_raw <- schard::h5ad2seurat(h5ad_file, use.raw = TRUE)

    # Compare with processed counts
    seurat_processed <- schard::h5ad2seurat(h5ad_file, use.raw = FALSE)

    cat("Raw counts summary:\n")
    print(seurat_raw)
    cat("Processed counts summary:\n")
    print(seurat_processed)

    # Compare count totals
    raw_totals <- colSums(seurat_raw)
    proc_totals <- colSums(seurat_processed)

    cat("Raw vs processed count correlation:", cor(raw_totals, proc_totals), "\n")

    return(list(raw = seurat_raw, processed = seurat_processed))
}

# Example 3: Spatial data conversion
convert_spatial_data <- function(h5ad_file) {
    cat("Converting spatial H5AD to Seurat\n")

    # Option 1: Single merged object
    spatial_merged <- schard::h5ad2seurat_spatial(h5ad_file, simplify = TRUE)

    # Option 2: List of objects per slide
    spatial_list <- schard::h5ad2seurat_spatial(h5ad_file, simplify = FALSE)

    cat("Merged spatial object:\n")
    print(spatial_merged)

    cat("List of spatial objects:\n")
    print(sapply(spatial_list, function(x) paste(ncol(x), "cells")))

    # Spatial plotting
    if (length(spatial_merged@images) > 0) {
        cat("Creating spatial plots\n")

        # Plot total counts
        spatial_plot <- Seurat::SpatialPlot(spatial_merged, features = "nCount_RNA")
        print(spatial_plot)

        # Plot for specific image if multiple
        image_names <- names(spatial_merged@images)
        if (length(image_names) > 1) {
            specific_plot <- Seurat::SpatialPlot(
                spatial_merged,
                features = "nCount_RNA",
                images = image_names[1]
            )
            print(specific_plot)
        }
    }

    return(list(merged = spatial_merged, list = spatial_list))
}

# Example 4: SingleCellExperiment conversion
convert_to_sce <- function(h5ad_file) {
    cat("Converting H5AD to SingleCellExperiment\n")

    # Load as SCE
    sce_obj <- schard::h5ad2sce(h5ad_file)

    # Basic inspection
    cat("SCE object summary:\n")
    print(sce_obj)

    # Check assays
    cat("Available assays:", paste(assayNames(sce_obj), collapse = ", "), "\n")

    # Check reduced dimensions
    if (length(reducedDims(sce_obj)) > 0) {
        cat("Available reduced dimensions:", paste(names(reducedDims(sce_obj)), collapse = ", "), "\n")

        # Plot first reduction
        rd_name <- names(reducedDims(sce_obj))[1]
        rd_data <- reducedDim(sce_obj, rd_name)

        if (ncol(rd_data) >= 2) {
            plot(rd_data[,1], rd_data[,2],
                 main = paste(rd_name, "plot"),
                 xlab = paste(rd_name, "1"),
                 ylab = paste(rd_name, "2"),
                 pch = 16, cex = 0.5)
        }
    }

    return(sce_obj)
}

# Example 5: ATAC-seq specific analysis
analyze_atac_data <- function(seurat_obj) {
    cat("Analyzing ATAC-seq data\n")

    # Check if this looks like ATAC data
    feature_names <- rownames(seurat_obj)
    is_atac <- mean(grepl(":", feature_names)) > 0.5

    if (is_atac) {
        cat("Detected ATAC-seq data (genomic coordinates)\n")

        # Basic ATAC QC if not already present
        if (!"nCount_ATAC" %in% colnames(seurat_obj@meta.data)) {
            seurat_obj$nCount_ATAC <- Matrix::colSums(seurat_obj@assays[[DefaultAssay(seurat_obj)]]@counts)
            seurat_obj$nFeature_ATAC <- Matrix::colSums(seurat_obj@assays[[DefaultAssay(seurat_obj)]]@counts > 0)
        }

        # Basic filtering
        cat("Applying basic ATAC-seq filtering\n")
        seurat_obj <- subset(
            seurat_obj,
            subset = nCount_ATAC > 1000 &
                     nCount_ATAC < 50000 &
                     nFeature_ATAC > 500
        )

        cat("After filtering:", ncol(seurat_obj), "cells remain\n")

        # Standard ATAC workflow if not already done
        if (!"lsi" %in% names(seurat_obj@reductions)) {
            cat("Running standard ATAC-seq workflow\n")

            # Use Signac for ATAC processing
            library(Signac)

            # Rename assay to ATAC if needed
            if (DefaultAssay(seurat_obj) != "ATAC") {
                seurat_obj[["ATAC"]] <- seurat_obj[[DefaultAssay(seurat_obj)]]
                DefaultAssay(seurat_obj) <- "ATAC"
            }

            # TF-IDF normalization
            seurat_obj <- RunTFIDF(seurat_obj)

            # Find top features
            seurat_obj <- FindTopFeatures(seurat_obj, min.cutoff = "q0")

            # SVD/LSI
            seurat_obj <- RunSVD(seurat_obj)

            # Clustering
            seurat_obj <- FindNeighbors(seurat_obj, reduction = "lsi", dims = 2:30)
            seurat_obj <- FindClusters(seurat_obj, algorithm = 3)

            # UMAP
            seurat_obj <- RunUMAP(seurat_obj, reduction = "lsi", dims = 2:30)

            cat("Completed standard ATAC-seq workflow\n")
        }
    } else {
        cat("Data does not appear to be ATAC-seq (no genomic coordinates detected)\n")
    }

    return(seurat_obj)
}

# Example 6: Quality control and comparison
quality_control_analysis <- function(h5ad_file) {
    cat("Performing quality control analysis\n")

    # Load both raw and processed
    seurat_raw <- schard::h5ad2seurat(h5ad_file, use.raw = TRUE)
    seurat_proc <- schard::h5ad2seurat(h5ad_file, use.raw = FALSE)

    # Compare basic statistics
    raw_counts <- Matrix::colSums(seurat_raw)
    proc_counts <- Matrix::colSums(seurat_proc)

    raw_features <- Matrix::colSums(seurat_raw > 0)
    proc_features <- Matrix::colSums(seurat_proc > 0)

    # Create comparison plots
    par(mfrow = c(2, 2))

    # Count comparison
    plot(raw_counts, proc_counts,
         main = "Raw vs Processed Counts",
         xlab = "Raw Counts", ylab = "Processed Counts",
         pch = 16, cex = 0.5)
    abline(0, 1, col = "red", lty = 2)

    # Feature comparison
    plot(raw_features, proc_features,
         main = "Raw vs Processed Features",
         xlab = "Raw Features", ylab = "Processed Features",
         pch = 16, cex = 0.5)
    abline(0, 1, col = "red", lty = 2)

    # Distribution plots
    hist(log10(raw_counts + 1), main = "Raw Counts Distribution",
         xlab = "log10(Counts + 1)", breaks = 50)
    hist(log10(proc_counts + 1), main = "Processed Counts Distribution",
         xlab = "log10(Counts + 1)", breaks = 50)

    par(mfrow = c(1, 1))

    # Summary statistics
    cat("\nQuality Control Summary:\n")
    cat("Raw data - Median counts per cell:", median(raw_counts), "\n")
    cat("Processed data - Median counts per cell:", median(proc_counts), "\n")
    cat("Raw data - Median features per cell:", median(raw_features), "\n")
    cat("Processed data - Median features per cell:", median(proc_features), "\n")
    cat("Count correlation:", cor(raw_counts, proc_counts), "\n")

    return(list(
        raw = seurat_raw,
        processed = seurat_proc,
        raw_counts = raw_counts,
        proc_counts = proc_counts
    ))
}

# Usage examples workflow:
# 1. Basic conversion
# seurat_obj <- convert_basic_seurat("data.h5ad")

# 2. Raw vs processed comparison
# comparison <- convert_raw_seurat("data.h5ad")

# 3. Spatial data analysis
# spatial_results <- convert_spatial_data("spatial_data.h5ad")

# 4. SingleCellExperiment conversion
# sce_obj <- convert_to_sce("data.h5ad")

# 5. ATAC-seq specific analysis
# atac_obj <- analyze_atac_data(seurat_obj)

# 6. Quality control
# qc_results <- quality_control_analysis("data.h5ad")

